### PR TITLE
Update ISSUE Template

### LINKED ISSUE #78: Add an Issue Template
Would like to see a well documented Issue template here.
Go through the project and make a tailored Issue template

### PR DESCRIPTION
**Pull request by vivekkj123**
# Description

Created an issue template for filing bug against this repo.

Fixes #78 

Addresses #78

### CODE REVIEW

**Comment by vivekkj123** [comment]
Also, please add hacktoberfest topic to this repo before merging my PR. else, my contribution won't count :(

**Comment by soham4abc** [comment]
Your work is awesome! Just a small request. Can you add another module named `feature request` just like you added Bug report!

@vivekkj123

**Comment by vivekkj123** [comment]
@soham4abc I've added template for feature request.

**Review by soham4abc — APPROVED** [review]
LGTM

**Comment by soham4abc** [comment]
Thanks a lot for your contribution @vivekkj123

**Pull request merged**
