### PR TITLE
added slowmode command

### PR DESCRIPTION
**Pull request by SCHW18TZ**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #---

Addresses #---

## Type of change

Added slowmode command

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
I tested it by running a test bot on the same code
- [ ] build(3.8)
- [ ] build(3.9)

**Test Configuration**:
* OS:
* OS Version:

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Additional Details:

### CODE REVIEW

**Review by danger-ahead — CHANGES_REQUESTED** [review]
Nice work. Please update the `COMMANDS.md` as well. So that we know how to use the command as well.

**Comment by SCHW18TZ** [comment]
to turn the slomode off you just need to write [prefix]slm 0

**Comment by SCHW18TZ** [comment]
I am sorry but where is the `COMMANDS.md` ?

**Comment by danger-ahead** [comment]
https://github.com/danger-ahead/roBOT/blob/master/docs/COMMANDS.md

Here it is.

**Comment by SCHW18TZ** [comment]
Thanks I will add it!

**Comment by SCHW18TZ** [comment]
Okay I did as you said and changed to `COMMANDS.md` you can merge now if you want to.

**Review by danger-ahead — APPROVED** [review]

**Pull request merged**
