### PR TITLE
#Resolved 89 Updating documentation part

### PR DESCRIPTION
**Pull request by VidhiBhatt01**
# Description

Updated the documentation by adding information about _compliment command in help.py and commands.md files.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] build(3.8)
- [x] build(3.9)

**Test Configuration**:
* OS: Windows10

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by soham4abc** [comment]
I am approving this PR. But from next time try to add the required feature and update it's documentation in a single PR. It's a healthy opensource practice

**Review by soham4abc — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
I assure you this mistake won't be repeated again.Thanks for approving.

**Comment by VidhiBhatt01** [comment]
Also can you please guide me why my code failed in run linters check , so that I can improve it next time?

**Comment by soham4abc** [comment]
> Also can you please guide me why my code failed in run linters check , so that I can improve it next time?

We use `black` lint check. After your work is done run `black .` in terminal to get your code re-formatted before commiting (Make sure black python package is installed) this helps us to maintain the code quality and hence makes it easier to contribute for others! Cheers!

**Comment by VidhiBhatt01** [comment]
Got it!

**Pull request merged**
