### PR TITLE
Fixed #70 - Lines indicating successful execution are missing

### LINKED ISSUE #70: Lines indicating successful execution are missing
#### You need to add two lines to make this happen. The lines to be added are provided in the following section.

The updated structure will be as follows:

```
elif message.content.startswith("$"):

    if message.author.guild_permissions.administrator:
        if:
            <all the lines originally under the `if` block go here>
            await message.add_reaction("\U0001f44d") #new line to be added under if
        else:
            <all the lines originally under `else` the block go here>
            await message.add_reaction("\U0001f44E") #new line to be added under else
```

### PR DESCRIPTION
**Pull request by Edald123**
# Description

Fixes #70, added lines indicating successful execution. 

## Type of change

- [x] Enhancement

### CODE REVIEW

**Review by danger-ahead — CHANGES_REQUESTED** [review]
Looks like you insterted the lines under the wrong `if-else` block.

The `if` is in line `43`, similarly the `else` is located in line `52`. Please make the necessary changes.

**Comment by Edald123** [comment]
Thank you!, I'll make the changes now.

**Comment by Edald123** [comment]
I think the changes are done, let me know if everything is ok, thank you!

**Review by soham4abc — APPROVED** [review]
LGTM!

**Review by danger-ahead — APPROVED** [review]

**Comment by danger-ahead** [comment]
Thanks @Edald123

**Comment by Edald123** [comment]
Of course, let me if I can help with anything else!

**Pull request merged**
